
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ColorType
    {
        /// <summary>
        /// 红色
        /// </summary>
        Red = 1,
        /// <summary>
        /// 蓝色
        /// </summary>
        Blue = 2,
        /// <summary>
        /// 黄色
        /// </summary>
        Yellow = 3,
    }

} 

