
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ItemConfig : Luban.BeanBase
{
    public ItemConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["type"].IsString) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["iconPath"].IsString) { throw new SerializationException(); }  IconPath = _buf["iconPath"]; }
    }

    public static ItemConfig DeserializeItemConfig(JSONNode _buf)
    {
        return new ItemConfig(_buf);
    }

    /// <summary>
    /// 注释行，读取就会掉过这行
    /// </summary>
    public readonly int Id;
    public readonly string Name;
    public readonly string Type;
    public readonly string IconPath;
   
    public const int __ID__ = -764023723;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "iconPath:" + IconPath + ","
        + "}";
    }
}

}

