
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class LevelConfig : Luban.BeanBase
{
    public LevelConfig(JSONNode _buf) 
    {
        { if(!_buf["Level"].IsNumber) { throw new SerializationException(); }  Level = _buf["Level"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["PrefabName"].IsString) { throw new SerializationException(); }  PrefabName = _buf["PrefabName"]; }
        { if(!_buf["BoxConfig"].IsString) { throw new SerializationException(); }  BoxConfig = _buf["BoxConfig"]; }
        { if(!_buf["iconPath"].IsString) { throw new SerializationException(); }  IconPath = _buf["iconPath"]; }
        { if(!_buf["iconGrayPath"].IsString) { throw new SerializationException(); }  IconGrayPath = _buf["iconGrayPath"]; }
        { if(!_buf["iconCollectPath"].IsString) { throw new SerializationException(); }  IconCollectPath = _buf["iconCollectPath"]; }
        { if(!_buf["iconCollectGrayPath"].IsString) { throw new SerializationException(); }  IconCollectGrayPath = _buf["iconCollectGrayPath"]; }
    }

    public static LevelConfig DeserializeLevelConfig(JSONNode _buf)
    {
        return new LevelConfig(_buf);
    }

    /// <summary>
    /// 注释行，读取就会掉过这行
    /// </summary>
    public readonly int Level;
    public readonly string Name;
    public readonly string PrefabName;
    public readonly string BoxConfig;
    public readonly string IconPath;
    public readonly string IconGrayPath;
    public readonly string IconCollectPath;
    public readonly string IconCollectGrayPath;
   
    public const int __ID__ = -1308229690;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Level:" + Level + ","
        + "Name:" + Name + ","
        + "PrefabName:" + PrefabName + ","
        + "BoxConfig:" + BoxConfig + ","
        + "iconPath:" + IconPath + ","
        + "iconGrayPath:" + IconGrayPath + ","
        + "iconCollectPath:" + IconCollectPath + ","
        + "iconCollectGrayPath:" + IconCollectGrayPath + ","
        + "}";
    }
}

}

