
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Player : Luban.BeanBase
{
    public Player(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["age"].IsNumber) { throw new SerializationException(); }  Age = _buf["age"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["height"].IsNumber) { throw new SerializationException(); }  Height = _buf["height"]; }
        { var __json0 = _buf["爱好"]; if(!__json0.IsArray) { throw new SerializationException(); } 爱好 = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  爱好.Add(__v0); }   }
    }

    public static Player DeserializePlayer(JSONNode _buf)
    {
        return new Player(_buf);
    }

    public readonly int Id;
    public readonly int Age;
    public readonly string Name;
    public readonly float Height;
    public readonly System.Collections.Generic.List<string> 爱好;
   
    public const int __ID__ = -1901885695;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "age:" + Age + ","
        + "name:" + Name + ","
        + "height:" + Height + ","
        + "爱好:" + Luban.StringUtil.CollectionToString(爱好) + ","
        + "}";
    }
}

}

