
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbTest TbTest {get; }
    public TbLevelConfig TbLevelConfig {get; }
    public TbPlayer TbPlayer {get; }
    public TbTestA TbTestA {get; }
    public TbTestEnum TbTestEnum {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbTest = new TbTest(loader("tbtest"));
        TbLevelConfig = new TbLevelConfig(loader("tblevelconfig"));
        TbPlayer = new TbPlayer(loader("tbplayer"));
        TbTestA = new TbTestA(loader("tbtesta"));
        TbTestEnum = new TbTestEnum(loader("tbtestenum"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbTest.ResolveRef(this);
        TbLevelConfig.ResolveRef(this);
        TbPlayer.ResolveRef(this);
        TbTestA.ResolveRef(this);
        TbTestEnum.ResolveRef(this);
    }
}

}
