
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbSingInConfig
{
    private readonly System.Collections.Generic.Dictionary<int, SingInConfig> _dataMap;
    private readonly System.Collections.Generic.List<SingInConfig> _dataList;
    
    public TbSingInConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SingInConfig>();
        _dataList = new System.Collections.Generic.List<SingInConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SingInConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = SingInConfig.DeserializeSingInConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SingInConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<SingInConfig> DataList => _dataList;

    public SingInConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SingInConfig Get(int key) => _dataMap[key];
    public SingInConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

