
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbTestEnum
{
    private readonly System.Collections.Generic.Dictionary<int, TestEnum> _dataMap;
    private readonly System.Collections.Generic.List<TestEnum> _dataList;
    
    public TbTestEnum(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TestEnum>();
        _dataList = new System.Collections.Generic.List<TestEnum>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TestEnum _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = TestEnum.DeserializeTestEnum(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TestEnum> DataMap => _dataMap;
    public System.Collections.Generic.List<TestEnum> DataList => _dataList;

    public TestEnum GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TestEnum Get(int key) => _dataMap[key];
    public TestEnum this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

