
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbTestA
{
    private readonly System.Collections.Generic.Dictionary<int, TestA> _dataMap;
    private readonly System.Collections.Generic.List<TestA> _dataList;
    
    public TbTestA(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TestA>();
        _dataList = new System.Collections.Generic.List<TestA>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TestA _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = TestA.DeserializeTestA(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TestA> DataMap => _dataMap;
    public System.Collections.Generic.List<TestA> DataList => _dataList;

    public TestA GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TestA Get(int key) => _dataMap[key];
    public TestA this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

