
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class TestA : Luban.BeanBase
{
    public TestA(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["age"].IsNumber) { throw new SerializationException(); }  Age = _buf["age"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["score"].IsNumber) { throw new SerializationException(); }  Score = _buf["score"]; }
    }

    public static TestA DeserializeTestA(JSONNode _buf)
    {
        return new TestA(_buf);
    }

    /// <summary>
    /// 注释行，读取就会掉过这行
    /// </summary>
    public readonly int Id;
    public readonly int Age;
    public readonly string Name;
    public readonly int Score;
   
    public const int __ID__ = 80698831;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "age:" + Age + ","
        + "name:" + Name + ","
        + "score:" + Score + ","
        + "}";
    }
}

}

