
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class TestEnum : Luban.BeanBase
{
    public TestEnum(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["color"].IsNumber) { throw new SerializationException(); }  Color = (ColorType)_buf["color"].AsInt; }
    }

    public static TestEnum DeserializeTestEnum(JSONNode _buf)
    {
        return new TestEnum(_buf);
    }

    public readonly int Id;
    public readonly ColorType Color;
   
    public const int __ID__ = -1082582829;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "color:" + Color + ","
        + "}";
    }
}

}

