
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Test : Luban.BeanBase
{
    public Test(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["age"].IsNumber) { throw new SerializationException(); }  Age = _buf["age"]; }
        { var __json0 = _buf["names"]; if(!__json0.IsArray) { throw new SerializationException(); } Names = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Names.Add(__v0); }   }
        { if(!_buf["score"].IsNumber) { throw new SerializationException(); }  Score = _buf["score"]; }
        { var __json0 = _buf["listNumber"]; if(!__json0.IsArray) { throw new SerializationException(); } ListNumber = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ListNumber.Add(__v0); }   }
        { var __json0 = _buf["arrayNumber"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; ArrayNumber = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ArrayNumber[__index0++] = __v0; }   }
        { var __json0 = _buf["mapNumber"]; if(!__json0.IsArray) { throw new SerializationException(); } MapNumber = new System.Collections.Generic.Dictionary<int, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  MapNumber.Add(_k0, _v0); }   }
    }

    public static Test DeserializeTest(JSONNode _buf)
    {
        return new Test(_buf);
    }

    /// <summary>
    /// 注释行，读取就会掉过这行
    /// </summary>
    public readonly int Id;
    public readonly int Age;
    public readonly System.Collections.Generic.List<string> Names;
    public readonly int Score;
    public readonly System.Collections.Generic.List<int> ListNumber;
    public readonly int[] ArrayNumber;
    public readonly System.Collections.Generic.Dictionary<int, int> MapNumber;
   
    public const int __ID__ = 2603186;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "age:" + Age + ","
        + "names:" + Luban.StringUtil.CollectionToString(Names) + ","
        + "score:" + Score + ","
        + "listNumber:" + Luban.StringUtil.CollectionToString(ListNumber) + ","
        + "arrayNumber:" + Luban.StringUtil.CollectionToString(ArrayNumber) + ","
        + "mapNumber:" + Luban.StringUtil.CollectionToString(MapNumber) + ","
        + "}";
    }
}

}

